In [16]:
# Setup

from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

g:\My Drive\Graduação e Pós\USP\MBA USP IA e Big Data\TCC\port_leadtime_prediction

In [17]:
# Imports

import pandas as pd

from src.data_sources.ports import load_port_files, process_ports
from src.data_sources.weather import load_weather_files, process_weather
from src.features.weather_features import (
    prepare_port_reference_for_weather,
    create_weather_history_features,
    merge_weather_features,
)

In [18]:
# Paths

internal_features_path = PROJECT_ROOT / "data" / "interim" / "internal_features.parquet"
raw_ports_dir = PROJECT_ROOT / "data" / "raw" / "ports"
raw_weather_dir = PROJECT_ROOT / "data" / "raw" / "weather"

df_internal = pd.read_parquet(internal_features_path)

print(df_internal.shape)
df_internal.head()

(141895, 69)

,port_call_id,port,port_name,imo,vessel_id,vessel_name,operation_type,source_port,source_port_name,destination_port,...,arrival_is_weekend,arrival_shift,arrival_season,avg_wait_prev_20_calls_port,avg_operation_prev_20_calls_port,std_wait_prev_20_calls_port,arrival_date,arrivals_same_day_port,arrivals_prev_day_port,arrivals_prev_7d_avg_port
0,561202021,BR052001,TERMINAL FLUVIAL DE JURUTI,9620310,<NA>,WHITE WHALE,Carga,BRAMW001,TERMINAL DA ALUMAR - SÃO LUIZ - MA,BR052,...,1,night,summer,NaN,NaN,NaN,2022-01-02,1,NaN,NaN
1,4172022,BR052001,TERMINAL FLUVIAL DE JURUTI,9304241,<NA>,GOOD HOPE MAX,Carga,BR052,JURUTI,BRAMW001,...,0,evening,summer,NaN,NaN,NaN,2022-01-06,1,1.0,NaN
2,7012022,BR052001,TERMINAL FLUVIAL DE JURUTI,9628922,<NA>,AMBERJACK,Carga,BRAMW001,TERMINAL DA ALUMAR - SÃO LUIZ - MA,BRAMW001,...,1,evening,summer,NaN,NaN,NaN,2022-01-08,1,1.0,NaN
3,12292022,BR052001,TERMINAL FLUVIAL DE JURUTI,9473339,<NA>,JURUTI,Carga,BRAMW001,TERMINAL DA ALUMAR - SÃO LUIZ - MA,BR052,...,0,morning,summer,NaN,NaN,NaN,2022-01-13,1,1.0,1.0
4,19472022,BR052001,TERMINAL FLUVIAL DE JURUTI,9620310,<NA>,WHITE WHALE,Carga,BR052,JURUTI,BR052,...,0,night,summer,NaN,NaN,NaN,2022-01-17,1,1.0,1.0

In [19]:
# Load and process ports data

df_ports_raw = load_port_files(raw_ports_dir)
df_ports = process_ports(df_ports_raw, coord_decimals=5)
df_ports = prepare_port_reference_for_weather(df_ports)

print(df_ports.shape)
df_ports.head()

(125, 9)

,port,port_name,city,state,region,latitude,longitude,latitude_r,longitude_r
0,BR052001,TERMINAL FLUVIAL DE JURUTI,JURITI,PA,NORTE,-2.173782,-56.105980,-2.17378,-56.10598
1,BR147001,TERMINAL PORTUÁRIO FLUVIAL - COPESUL,TRIUNFO,RS,SUL,-29.948610,-51.623888,-29.94861,-51.62389
2,BR252001,TERMINAL AQUAVIARIO DE GUAMARE - TRANSPETRO,GUAMARÉ,RN,NORDESTE,-4.873611,-36.374166,-4.87361,-36.37417
3,BR252002,TERM AQUAVIARIO DE GUAMARE - 3R OPERAÇÕES MARI...,GUAMARÉ,RN,NORDESTE,-5.106387,-36.317918,-5.10639,-36.31792
4,BR302002,TUP NSR,NOVA SANTA RITA,RS,SUL,-29.931204,-51.282781,-29.93120,-51.28278

In [20]:
# Load and process weather data

df_weather_raw = load_weather_files(raw_weather_dir)
df_weather = process_weather(df_weather_raw, coord_decimals=5)

print(df_weather.shape)
df_weather.head()

(161117, 14)

,latitude,longitude,date,temperature_2m_mean,temperature_2m_max,temperature_2m_min,precipitation_sum,rain_sum,precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,latitude_r,longitude_r
0,-32.122222,-52.093333,2021-06-15,14.0,15.9,12.9,0.0,0.0,0.0,34.4,46.1,203,-32.12222,-52.09333
1,-32.122222,-52.093333,2021-06-16,12.5,13.3,11.8,0.0,0.0,0.0,33.6,46.1,203,-32.12222,-52.09333
2,-32.122222,-52.093333,2021-06-17,12.0,12.5,11.5,0.7,0.7,4.0,21.3,28.8,222,-32.12222,-52.09333
3,-32.122222,-52.093333,2021-06-18,12.7,14.1,11.7,0.1,0.1,1.0,16.9,25.9,140,-32.12222,-52.09333
4,-32.122222,-52.093333,2021-06-19,14.5,14.9,13.8,6.6,6.6,22.0,29.1,34.2,69,-32.12222,-52.09333

In [21]:
# Creating weather history

df_weather_feat = create_weather_history_features(df_weather)

print(df_weather_feat.shape)
df_weather_feat.head()

(161117, 29)

,latitude,longitude,date,temperature_2m_mean,temperature_2m_max,temperature_2m_min,precipitation_sum,rain_sum,precipitation_hours,wind_speed_10m_max,...,rain_sum_prev_3d,precipitation_hours_prev_3d,temperature_2m_mean_prev_3d,wind_speed_10m_max_prev_3d,wind_gusts_10m_max_prev_3d,rain_sum_prev_7d,precipitation_hours_prev_7d,temperature_2m_mean_prev_7d,wind_speed_10m_max_prev_7d,wind_gusts_10m_max_prev_7d
0,-32.122222,-52.093333,2021-06-15,14.0,15.9,12.9,0.0,0.0,0.0,34.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-32.122222,-52.093333,2021-06-16,12.5,13.3,11.8,0.0,0.0,0.0,33.6,...,0.0,0.0,14.000000,34.4,46.1,NaN,NaN,NaN,NaN,NaN
2,-32.122222,-52.093333,2021-06-17,12.0,12.5,11.5,0.7,0.7,4.0,21.3,...,0.0,0.0,13.250000,34.4,46.1,NaN,NaN,NaN,NaN,NaN
3,-32.122222,-52.093333,2021-06-18,12.7,14.1,11.7,0.1,0.1,1.0,16.9,...,0.7,4.0,12.833333,34.4,46.1,0.7,4.0,12.833333,34.4,46.1
4,-32.122222,-52.093333,2021-06-19,14.5,14.9,13.8,6.6,6.6,22.0,29.1,...,0.8,5.0,12.400000,33.6,46.1,0.8,5.0,12.800000,34.4,46.1

In [22]:
# Merge to the analytical dataset

df_eda = merge_weather_features(
    df=df_internal,
    weather_df=df_weather_feat,
    ports_df=df_ports,
)

print(df_eda.shape)
df_eda.head()

(141895, 104)

,port_call_id,port,port_name_x,imo,vessel_id,vessel_name,operation_type,source_port,source_port_name,destination_port,...,temperature_2m_mean_prev_3d,wind_speed_10m_max_prev_3d,wind_gusts_10m_max_prev_3d,rain_sum_prev_7d,precipitation_hours_prev_7d,temperature_2m_mean_prev_7d,wind_speed_10m_max_prev_7d,wind_gusts_10m_max_prev_7d,has_port_reference,has_weather_data
0,561202021,BR052001,TERMINAL FLUVIAL DE JURUTI,9620310,<NA>,WHITE WHALE,Carga,BRAMW001,TERMINAL DA ALUMAR - SÃO LUIZ - MA,BR052,...,26.466667,11.5,26.6,142.2,89.0,26.914286,14.2,31.7,1,1
1,4172022,BR052001,TERMINAL FLUVIAL DE JURUTI,9304241,<NA>,GOOD HOPE MAX,Carga,BR052,JURUTI,BRAMW001,...,25.966667,8.9,23.4,159.9,111.0,26.242857,12.2,27.7,1,1
2,7012022,BR052001,TERMINAL FLUVIAL DE JURUTI,9628922,<NA>,AMBERJACK,Carga,BRAMW001,TERMINAL DA ALUMAR - SÃO LUIZ - MA,BRAMW001,...,26.233333,9.2,26.6,162.8,119.0,25.900000,12.2,27.7,1,1
3,12292022,BR052001,TERMINAL FLUVIAL DE JURUTI,9473339,<NA>,JURUTI,Carga,BRAMW001,TERMINAL DA ALUMAR - SÃO LUIZ - MA,BR052,...,26.700000,9.6,24.1,66.8,99.0,26.114286,10.6,26.6,1,1
4,19472022,BR052001,TERMINAL FLUVIAL DE JURUTI,9620310,<NA>,WHITE WHALE,Carga,BR052,JURUTI,BR052,...,27.400000,13.6,29.9,31.3,74.0,27.042857,13.6,29.9,1,1

In [23]:
df_eda["has_port_reference"].value_counts(dropna=False)

has_port_reference
1    141895
Name: count, dtype: Int64

In [24]:
df_eda["has_weather_data"].value_counts(dropna=False)

has_weather_data
1    141844
0        51
Name: count, dtype: Int64

In [25]:
# Analyze missingness in the new columns

weather_cols = [
    "city",
    "state",
    "region",
    "temperature_2m_mean",
    "temperature_2m_max",
    "temperature_2m_min",
    "precipitation_sum",
    "rain_sum",
    "precipitation_hours",
    "wind_speed_10m_max",
    "wind_gusts_10m_max",
    "wind_direction_10m_dominant",
    "rain_sum_prev_1d",
    "temperature_2m_mean_prev_3d",
    "wind_speed_10m_max_prev_3d",
    "rain_sum_prev_7d",
    "wind_gusts_10m_max_prev_7d",
]

df_eda[weather_cols].isna().mean().sort_values(ascending=False)

temperature_2m_mean_prev_3d    0.000381
rain_sum_prev_1d               0.000381
wind_speed_10m_max_prev_3d     0.000381
rain_sum_prev_7d               0.000381
wind_gusts_10m_max_prev_7d     0.000381
temperature_2m_min             0.000359
temperature_2m_max             0.000359
precipitation_sum              0.000359
temperature_2m_mean            0.000359
wind_speed_10m_max             0.000359
wind_direction_10m_dominant    0.000359
precipitation_hours            0.000359
rain_sum                       0.000359
wind_gusts_10m_max             0.000359
city                           0.000000
region                         0.000000
state                          0.000000
dtype: float64

In [26]:
df_eda[df_eda["has_weather_data"] == False]

,port_call_id,port,port_name_x,imo,vessel_id,vessel_name,operation_type,source_port,source_port_name,destination_port,...,temperature_2m_mean_prev_3d,wind_speed_10m_max_prev_3d,wind_gusts_10m_max_prev_3d,rain_sum_prev_7d,precipitation_hours_prev_7d,temperature_2m_mean_prev_7d,wind_speed_10m_max_prev_7d,wind_gusts_10m_max_prev_7d,has_port_reference,has_weather_data
15168,105612013,BRFOR,FORTALEZA (MUCURIPE),8716241,<NA>,WS ITAQUI,Solicitação de certificado,BRFOR,FORTALEZA (MUCURIPE),<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
15169,13742020,BRFOR,FORTALEZA (MUCURIPE),<NA>,182-002087-8,ARAXÁ,Solicitação de certificado,BRNAT,NATAL,BRNAT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
15170,469412020,BRFOR,FORTALEZA (MUCURIPE),9668697,3813896897,SAAM PAITER,Solicitação de certificado,BRPEC,PECEM,BRBEL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
15171,478392020,BRFOR,FORTALEZA (MUCURIPE),8716227,1210104814,ENGENHEIRO MASCARENHAS,Solicitação de certificado,BRFOR,FORTALEZA (MUCURIPE),<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
15172,188182021,BRFOR,FORTALEZA (MUCURIPE),<NA>,3813876454,WS VIRGO,Abastecimento (Bunker),BRFOR,FORTALEZA (MUCURIPE),BRFOR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
17137,142952021,BRIBB,IMBITUBA,9440617,4019900671,DRACO,Desembarque/Embarque de Passageiros,BRITJ,ITAJAI,BRSSZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
26889,244412019,BRITJ,ITAJAI,<NA>,381-387544-0,ITABIRA,Solicitação de certificado,BRVIX,VITÓRIA,BRSUA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
26890,332022019,BRITJ,ITAJAI,9188130,<NA>,BRAM NATAL,Solicitação de certificado,BRRIO,RIO DE JANEIRO,BRNTR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
26891,13962021,BRITJ,ITAJAÍ,9664299,443-048077-0,BRAM BRASILIA,Solicitação de certificado,BRRIO,RIO DE JANEIRO,BRRIO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
26892,44622021,BRITJ,ITAJAÍ,9696802,<NA>,STARNAV AQUARIUS,Solicitação de certificado,BRRIO,RIO DE JANEIRO,BRRIO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
26893,106312021,BRITJ,ITAJAÍ,9759472,4430489017,STARNAV CEPHEUS,Off-shore,BRRJ022,PORTO DO AÇU,BRRIO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
26894,119422021,BRITJ,ITAJAÍ,<NA>,3813880257,STARNAV PEGASUS,Solicitação de certificado,BRPNG,PARANAGUA,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
26895,167592021,BRITJ,ITAJAÍ,9423217,<NA>,CAMPOS COMMANDER,Off-shore,BRRIO,RIO DE JANEIRO,BRRJ022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
26896,164132021,BRITJ,ITAJAÍ,9668659,381-389071-6,SAAM PATAXÓ,Solicitação de certificado,BRITJ,ITAJAÍ,BRITJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
26897,199982021,BRITJ,ITAJAÍ,9696802,<NA>,STARNAV AQUARIUS,Solicitação de certificado,BRRIO,RIO DE JANEIRO,BRRIO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
26898,204022021,BRITJ,ITAJAÍ,9759484,<NA>,STARNAV CYGNUS,Solicitação de certificado,BRRIO,RIO DE JANEIRO,BRRIO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
26899,194702021,BRITJ,ITAJAÍ,9271767,3810508055,ALFANAVE CABO FRIO,Solicitação de certificado,BRITJ,ITAJAÍ,BRITJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
34438,385112017,BRNTR,NITERÓI,9468657,3813907538,GNL 1015,Off-shore,BRRIO,RIO DE JANEIRO,BRSAS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
34439,495682022,BRNTR,NITERÓI,9468657,3813907538,GNL 1015,Off-shore,BRRIO,RIO DE JANEIRO,BRSAS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
38403,396072020,BRPEC,PECEM,9315434,<NA>,WS LYNX,Solicitação de certificado,BRPEC,PECEM,BRSSA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
44256,141542021,BRPNG,PARANAGUA,<NA>,102150423,VIGO MAXIMUS,Off-shore,BRRIO,RIO DE JANEIRO,BRRIO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
44257,153822021,BRPNG,PARANAGUA,<NA>,3810205028,BENJAMIM ABRAHAO,Off-shore,BRVIX021,TBO - TERMINAL BARCAÇAS OCEÂNICAS ARCELORMITTA...,BRNVT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
53592,79212021,BRREC,RECIFE,9307695,3810510441,WS LEONIS,Solicitação de certificado,BRREC,RECIFE,BRCDO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
53593,286692022,BRREC,RECIFE,9307695,3810510441,WS LEONIS,"Off-shore,Solicitação de certificado",BRREC,RECIFE,BRCDO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60397,291322015,BRRIO,RIO DE JANEIRO,<NA>,2810244901,SN PALMARES,<NA>,BRNTR,NITERÓI,BRMCZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60398,331022015,BRRIO,RIO DE JANEIRO,9333503,3813916782,Z MAX XXIX,Off-shore,BRRIO,RIO DE JANEIRO,BRNTR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60399,537372023,BRRIO,RIO DE JANEIRO,9333503,3813916782,Z MAX XXIX,Off-shore,BRRIO,RIO DE JANEIRO,BRNTR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60400,432812016,BRRIO,RIO DE JANEIRO,9273258,3810512036,AUSTRAL ABROLHOS,<NA>,BRRIO,RIO DE JANEIRO,BRCAM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60401,110982016,BRRIO,RIO DE JANEIRO,9055113,<NA>,SÃO LUIZ,Off-shore,BRRIO,RIO DE JANEIRO,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60402,293412017,BRRIO,RIO DE JANEIRO,9334179,<NA>,CAPTAIN NICHOLAS Z,Off-shore,BRRIO,RIO DE JANEIRO,BRRIO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60403,286632018,BRRIO,RIO DE JANEIRO,9440681,3813872122,SKUA,Off-shore,BRMEA,MACAÉ,BRNTR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60404,18112020,BRRIO,RIO DE JANEIRO,9604902,3813882713,SIEM PENDOTIBA,Off-shore,BRVIX025,TEMINAL DE BENTO FERREIRA - BERÇO 909 - ZEMAX,BRRIO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60405,111472020,BRRIO,RIO DE JANEIRO,<NA>,3813901718,LUIZ REBELO III,"Fundeio,Off-shore",BRZZZ,MADRE DE DEUS,BRRIO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60406,127942020,BRRIO,RIO DE JANEIRO,9687796,3813887782,LOCAR LH XX,Solicitação de certificado,BRCAM,BACIA PETROLIFERA DE CAMPOS,BRRIO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60407,156152020,BRRIO,RIO DE JANEIRO,9604897,3813879038,SIEM PIATÃ,Off-shore,BRESP,BACIA PETROLÍFERO DO ESPIRITO SANTO,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60408,356842019,BRRIO,RIO DE JANEIRO,9426972,<NA>,CBO BIANCA,Off-shore,BRRIO,RIO DE JANEIRO,BRRIO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60409,356142020,BRRIO,RIO DE JANEIRO,9007178,381E010791,AMAZON CHIEFTAIN,Off-shore,BRRIO,RIO DE JANEIRO,BRRIO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60410,63742021,BRRIO,RIO DE JANEIRO,9336361,3410239146,TS ABROLHOS,Off-shore,BRVIX018,PORTOCEL - TERMINAL BARRA DO RIACHO - ES,BRVIX008,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60411,63732021,BRRIO,RIO DE JANEIRO,9278894,3410233385,TS CARAVELAS,Off-shore,BRVIX018,PORTOCEL - TERMINAL BARRA DO RIACHO - ES,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
60412,186782021,BRRIO,RIO DE JANEIRO,<NA>,3813872998,TS MARRENTO,Off-shore,BRRIO,RIO DE JANEIRO,BRRJ022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
108635,153162021,BRSSZ,SANTOS,9205316,4010812656,PLUTÃO,Solicitação de certificado,BRIBB,IMBITUBA,BRSSZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
108636,198142021,BRSSZ,SANTOS,9573189,3813880371,CRATER,Solicitação de certificado,BRADR,ANGRA DOS REIS,BRSSZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
108637,208572021,BRSSZ,SANTOS,9679218,3813902331,WS CYGNUS,Solicitação de certificado,BRSSO,SÃO SEBASTIAO,BRRIO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
126567,286712017,BRSUA,SUAPE,<NA>,121E000494,No Woman No Cry,Off-shore,BRRIO,RIO DE JANEIRO,BRVIX026,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
126568,47182020,BRSUA,SUAPE,9307695,381-051-044-1,WS LEONIS,Desembarque/Embarque de Passageiros,BRBAR,BARRA DOS COQUEIROS,BRCDO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
126569,556312021,BRSUA,SUAPE,9353242,<NA>,BW Princess,Carga e Descarga,ESALG,ALGECIRAS,ANCUR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
126570,182412020,BRSUA,SUAPE,9307968,<NA>,WS AQUILA,Solicitação de certificado,BRREC,RECIFE,BRCDO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
126571,454672020,BRSUA,SUAPE,9353242,<NA>,BW PRINCESS,Carga e Descarga,ESALG,ALGECIRAS,BRSSA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
126572,85202024,BRSUA,SUAPE,9787883,3813908909,SVITZER SONIA,Off-shore,BRAJU,PORTO BARRA DOS COQUEIROS - ARACAJU - SE,BRSUA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
126573,218902021,BRSUA,SUAPE,9787883,3813908909,SVITZER SONIA,Off-shore,BRAJU,PORTO BARRA DOS COQUEIROS - ARACAJU - SE,BRSUA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0
135767,221152015,BRVIX,VITÓRIA,9542520,<NA>,CS CALLA,Descarga,BRBAR,BARRA DOS COQUEIROS,PLSZZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0

In [ ]:
# Manual check

cols = [
    "port",
    "city",
    "state",
    "region",
    "arrival_port_ts",
    "arrival_date",
    "latitude_r",
    "longitude_r",
    "rain_sum",
    "rain_sum_prev_3d",
    "wind_speed_10m_max",
    "wind_gusts_10m_max_prev_7d",
]

df_eda[cols].head(20)

,port,city,state,region,arrival_port_ts,arrival_date,latitude_r,longitude_r,rain_sum,rain_sum_prev_3d,wind_speed_10m_max,wind_gusts_10m_max_prev_7d
0,BR052001,JURITI,PA,NORTE,2022-01-02 00:24:00,2022-01-02,-2.17378,-56.10598,8.2,106.3,12.2,31.7
1,BR052001,JURITI,PA,NORTE,2022-01-06 23:54:00,2022-01-06,-2.17378,-56.10598,13.3,45.4,7.9,27.7
2,BR052001,JURITI,PA,NORTE,2022-01-08 21:06:00,2022-01-08,-2.17378,-56.10598,23.7,29.6,10.6,27.7
3,BR052001,JURITI,PA,NORTE,2022-01-13 11:50:00,2022-01-13,-2.17378,-56.10598,4.2,12.8,12.4,26.6
4,BR052001,JURITI,PA,NORTE,2022-01-17 00:18:00,2022-01-17,-2.17378,-56.10598,21.4,14.3,8.7,29.9
5,BR052001,JURITI,PA,NORTE,2022-01-20 12:00:00,2022-01-20,-2.17378,-56.10598,1.2,57.6,15.8,32.0
6,BR052001,JURITI,PA,NORTE,2022-01-25 11:30:00,2022-01-25,-2.17378,-56.10598,6.1,47.1,11.2,38.5
7,BR052001,JURITI,PA,NORTE,2022-01-26 17:36:00,2022-01-26,-2.17378,-56.10598,21.9,42.8,10.2,38.5
8,BR052001,JURITI,PA,NORTE,2022-01-30 02:00:00,2022-01-30,-2.17378,-56.10598,3.6,65.3,12.7,34.2
9,BR052001,JURITI,PA,NORTE,2022-01-31 14:00:00,2022-01-31,-2.17378,-56.10598,3.3,24.6,9.6,34.2
10,BR052001,JURITI,PA,NORTE,2022-02-06 17:06:00,2022-02-06,-2.17378,-56.10598,56.9,33.7,12.2,36.4
11,BR052001,JURITI,PA,NORTE,2022-02-07 21:40:00,2022-02-07,-2.17378,-56.10598,2.9,84.9,7.4,36.4
12,BR052001,JURITI,PA,NORTE,2022-02-09 10:54:00,2022-02-09,-2.17378,-56.10598,13.8,69.0,5.7,36.4
13,BR052001,JURITI,PA,NORTE,2022-02-11 01:48:00,2022-02-11,-2.17378,-56.10598,15.7,36.7,10.4,27.7
14,BR052001,JURITI,PA,NORTE,2022-02-13 07:50:00,2022-02-13,-2.17378,-56.10598,8.4,54.3,9.4,27.7
15,BR052001,JURITI,PA,NORTE,2022-02-18 14:32:00,2022-02-18,-2.17378,-56.10598,65.6,68.4,8.0,31.3
16,BR052001,JURITI,PA,NORTE,2022-02-21 00:06:00,2022-02-21,-2.17378,-56.10598,4.7,74.5,9.7,31.3
17,BR052001,JURITI,PA,NORTE,2022-02-25 16:00:00,2022-02-25,-2.17378,-56.10598,6.9,25.8,16.7,37.8
18,BR052001,JURITI,PA,NORTE,2022-03-02 00:46:00,2022-03-02,-2.17378,-56.10598,1.9,56.1,13.6,29.2
19,BR052001,JURITI,PA,NORTE,2022-03-03 15:40:00,2022-03-03,-2.17378,-56.10598,4.6,38.5,11.9,29.2

In [ ]:
# Saving

interim_dir = PROJECT_ROOT / "data" / "interim"
processed_dir = PROJECT_ROOT / "data" / "processed"

interim_dir.mkdir(parents=True, exist_ok=True)
processed_dir.mkdir(parents=True, exist_ok=True)

ports_clean_path = interim_dir / "ports_clean.parquet"
weather_clean_path = interim_dir / "weather_clean.parquet"
weather_features_path = interim_dir / "weather_features.parquet"
eda_base_path = processed_dir / "eda_base.parquet"

df_ports.to_parquet(ports_clean_path, index=False)
df_weather_feat.to_parquet(weather_clean_path, index=False)
df_eda.to_parquet(weather_features_path, index=False)
df_eda.to_parquet(eda_base_path, index=False)

print(f"Ports clean saved to: {ports_clean_path}")
print(f"Weather clean saved to: {weather_clean_path}")
print(f"Weather features saved to: {weather_features_path}")
print(f"EDA base saved to: {eda_base_path}")